#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 22 14:58:53 CEST 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Accumulator_MultiDMA_tb_behav -key {Behavioral:sim_1:Functional:Accumulator_MultiDMA_tb} -tclbatch Accumulator_MultiDMA_tb.tcl -protoinst "protoinst_files/bd_6c3f.protoinst" -view /home/yuhaoliu/Projects/Verilog/AXI-MultiDMA-Ultra96V2/src/sim/Accumulator_MultiDMA_tb_behav.wcfg -log simulate.log"
xsim Accumulator_MultiDMA_tb_behav -key {Behavioral:sim_1:Functional:Accumulator_MultiDMA_tb} -tclbatch Accumulator_MultiDMA_tb.tcl -protoinst "protoinst_files/bd_6c3f.protoinst" -view /home/yuhaoliu/Projects/Verilog/AXI-MultiDMA-Ultra96V2/src/sim/Accumulator_MultiDMA_tb_behav.wcfg -log simulate.log

